### ISSUE TITLE
A question about the output of the network

### ISSUE THREAD

**Issue by ShougangShen** [LZGMatrix/BOP19_CDPN_2019ICCV#5]
Hello, Mr Li. Sorry to be a bother. I want to ask why the output channel of the network is 2+195=197? I carefully read the code, If I don't get it wrong, I know the first 2 channels is confidence map and the second 195=65*3 channels is coordinate map that describe x y z map respectively. Why are there 65 channels for x y z map respectively?
At test time, I find that you get the final coordinate-confidence map using argmax like this:
`output_coor_ = np.stack([np.argmax(output_coor_x_, axis=0),
                                     np.argmax(output_coor_y_, axis=0),
                                     np.argmax(output_coor_z_, axis=0)], axis=2)`

`output_conf_ = np.argmax(output_conf_, axis=0)`
I observed  that the file 'cfg.yaml' contain the 'coor_bin=64', how to understand this set? The final question is how to set the ground truth when training the network?  Looking forward to your reply.

**Comment by LZGMatrix** [comment]
In the 65 coordinates channels, 64 channels are used as valid coordinates and an additional channel is for the background. For the second question, what do you mean about how to set the ground truth?

**Comment by ShougangShen** [comment]
Thanks for your reply. Yeah, I mean that how to set the ground truth for valid coordinates and confidence. When you take a image, how to get the ground truth 3D coordinates of the objects pixels? Because the  perspective projection and self-occlusion, there may be multiple 3D points corresponding to one pixel. Is z-buffer algorithm used for valid coordinates? If not, how do you deal with it?

**Comment by LZGMatrix** [comment]
Yes, I used the z-buffer algorithm.

**Comment by ShougangShen** [comment]
OK, thank you.
